evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/MeasureEvaluation.java
minor bug preventing the `evaluator.measure` module from compiling.
=> fix merge issue

.gitignore, evaluator.measure-hapi/pom.xml, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureEvaluation.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/stu3/Stu3MeasureEvaluation.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/BaseMeasureEvaluationTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureEvaluationTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/stu3/Stu3MeasureEvaluationTest.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/MeasureEvaluation.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/MeasureInfo.java
I pulled over SDE logic from cqf-ruler and made it reusable across different FHIR versions / models. I added some basic unit tests to verify the things that I changed, but those could be fleshed out quite a bit more.
=> Implement support for supplemental data

.vscode/settings.json, README.MD, evaluator.activitydefinition/pom.xml, evaluator.builder/pom.xml, evaluator.cli/pom.xml, evaluator.cli/src/test/java/org/opencds/cqf/cql/evaluator/cli/CliTest.java, evaluator.content-test/pom.xml, evaluator.cql2elm/pom.xml, evaluator.dagger/pom.xml, evaluator.engine/pom.xml, evaluator.engine/src/main/java/org/opencds/cqf/cql/evaluator/engine/retrieve/BundleRetrieveProvider.java, evaluator.engine/src/main/java/org/opencds/cqf/cql/evaluator/engine/terminology/BundleTerminologyProvider.java, evaluator.expression/pom.xml, evaluator.fhir/pom.xml, evaluator.library/pom.xml, evaluator.measure-hapi/pom.xml, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/SimpleMeasureProcessorTest.java, evaluator.measure/pom.xml, evaluator.serialization/pom.xml, evaluator.spring/pom.xml, evaluator/pom.xml, pom.xml
* Rev to 1.3.0-SNAPSHOT to reflect new Measure / Expression eval functionality in the version
* Rework some log levels to better reflect actual importance
* Fix some build flakiness
=> Prep for 1.3.0 Release

evaluator/src/main/java/org/opencds/cqf/cql/evaluator/engine/util/TranslatorOptionsUtil.java
Solving for an `elm/json` library with: 
```
"annotation" : [ {
"translatorOptions" : ""
} ]
```
Which gives 
```
java.lang.IllegalArgumentException: No enum constant org.cqframework.cql.cql2elm.CqlTranslator.Options.
at java.lang.Enum.valueOf(Enum.java:257)
at org.cqframework.cql.cql2elm.CqlTranslator$Options.valueOf(CqlTranslator.java:38)
at org.opencds.cqf.cql.evaluator.engine.util.TranslatorOptionsUtil.parseTranslatorOptions(TranslatorOptionsUtil.java:117)
at org.opencds.cqf.cql.evaluator.engine.util.TranslatorOptionsUtil.getTranslatorOptions(TranslatorOptionsUtil.java:41)
at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.translatorOptionsMatch(TranslatingLibraryLoader.java:101)
at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.load(Tra …
```
=> QuickFix for Empty translatorOptions

evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/dstu3/Dstu3MeasureReportBuilder.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureReportBuilder.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/MeasureProcessorSdeAddCriteriaExtensionTest.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/MeasureConstants.java
The output MeasureReport extension looks like this:
=> Add extension to suplemental Data evaluated resources

evaluator.fhir/pom.xml, evaluator.measure-hapi/pom.xml, evaluator/pom.xml, pom.xml
Moves jcl-over-slf4j to test scope.
Moves Caffeine to test scope.
Removes hapi-fhir-client (still available from org.opencds.cqf.cql:engine.fhir:2.0.0)
Removes javax.annotations (I am not sure why this was here)
Centralizes FHIR Dependencies on the evaluator.fhir, where they are actually being used.
=> Dependency clean up

evaluator.activitydefinition/pom.xml, evaluator.builder/src/main/java/org/opencds/cqf/cql/evaluator/builder/CqlEvaluatorBuilder.java, evaluator.expression/pom.xml, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/AdditionalRequestHeadersInterceptor.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/ClientFactory.java, evaluator.jackson-deps/pom.xml, evaluator.jaxb-deps/pom.xml, evaluator.library/pom.xml, evaluator.measure-hapi/pom.xml, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/dstu3/Dstu3MeasureProcessor.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureProcessor.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/BaseMeasureEvaluationTest.java, evaluator.plandefinition/pom.xml, evaluator/src/main/java/org/opencds/cqf/cql/evaluator/cql2elm/model/CacheAwareModelManager.java, evaluator/src/main/java/org/opencds/cqf/cql/evaluator/engine/execution/TranslatingLibraryLoader.java, evaluator/src/test/java/org/opencds/cqf/cql/evaluator/cql2elm/model/CacheAwareModelManagerTests.java, pom.xml
1. Adding the new engine.jackson module to the POM
2. Using Service Loaders in the Translating Library Loader (using only jackson and JSON libs for now)
3. Using our own interceptor for the Rest Client (since we are not using HAPI-FHIR-Client anymore). 
4. Renaming VersionIdentifier to ModelIdentifier (Translator 2.1)
5. Adding javax.json when using Moxy
=> Engine 2.0 w jackson module upgrade

evaluator.activitydefinition/pom.xml, evaluator.builder/pom.xml, evaluator.dagger/pom.xml, evaluator.expression/pom.xml, evaluator.fhir/pom.xml, evaluator.library/pom.xml, evaluator.measure-hapi/pom.xml, evaluator.measure/pom.xml, evaluator.plandefinition/pom.xml, evaluator/pom.xml, evaluator/src/main/java/org/opencds/cqf/cql/evaluator/engine/execution/TranslatingLibraryLoader.java, pom.xml
This PR formalizes this project's compliance with Android APIs
1. Adds an Animal Sniffer plugin to check compliance with any runtime API when running `mvn test`
2. Selects modules `evaluator`, `evaluator.activitydefinition`, `evaluator.builder`, `evaluator.dagger`, `evaluator.expression`, `evaluator.fhir`, `evaluator.library`, `evaluator.measure`, `evaluator.measure-hapi`, `evaluator.plandefinition` to be checked for Android compliance. 
3. Establishes initial compliance to Android 8 - SDK 26, the minimum Android version the Translator is currently fully compliant with. 
**Important**: The plugin only verifies the source code in this project, not dependencies. 
For testing, add: 
```java
if (Optional.of(UUID.randomUUID()).isEmpty())
throw new RuntimeException("Test");
```
in the desired …
=> Formalizes compliance with Android 8, SDK 26 (2017+)

evaluator.expression/src/main/java/org/opencds/cqf/cql/evaluator/expression/ExpressionEvaluator.java, evaluator.library/src/main/java/org/opencds/cqf/cql/evaluator/library/LibraryProcessor.java, evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/dstu3/PlanDefinitionProcessor.java, evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessor.java, evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/r5/PlanDefinitionProcessor.java
Fixes to enable resolution for https://github.com/DBCG/cqf-ruler/issues/539
Fixes issue with LibraryProcessor not accounting for reference-styled patient IDs (e.g. Patient/example-patient)
Fixes issue with PlanDefinitionProcessor not resolving expression evaluation correctly - assumes the expression will be an identifier
Also cleaned up a bunch of warnings
=> Fixes for downstream CDSHooks update 

evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessor.java, evaluator.plandefinition/src/test/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessorTests.java, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-visit/anc_visit_bundle.json, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-visit/anc_visit_careplan.json, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-visit/anc_visit_patient.json, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-visit/anc_visit_plan_definition.json
The fhir-path specs allows to use [contained resources into plan-definition](https://hl7.org/fhir/R4/plandefinition-example.json.html) for better organization of dependent resources like ActivityDefinition. This is especially helpful and clean when using multiple ActivityDefinitions for a PlanDefinition. The current code despite allowing and parsing the local-ids (at L355) in method applyActivityDefinition does not work with local contained resources and fails before due to not being able to parse resource name
=> Fix resource type resolution from contained resources

evaluator/src/main/java/org/opencds/cqf/cql/evaluator/engine/execution/TranslatingLibraryLoader.java
this section is repetitive in libraryManager.resolveLibrary()
use setting enableCqlOnly to true to remove redundancy
=> remove redundant execution

evaluator.fhir/src/test/java/org/opencds/cqf/cql/evaluator/engine/retrieve/BundleRetrieveProviderTests.java
Use more concise assertions in BundleRetrieveProvider.java. For example, rely on the fact that Matchers.contains() ensures that the iterable size matches the number of items passed to contains().
=> Concise assertions in BundleRetrieveProvider.java

evaluator.plandefinition/src/test/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessorTests.java, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-dak/data-bundle.json, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-dak/output-careplan.json, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-dak/terminology-bundle.json, evaluator/src/main/java/org/opencds/cqf/cql/evaluator/engine/execution/TranslatingLibraryLoader.java
I am not 100% sure that the solution I implemented is ideal, but it does work.
- Added namespace preservation logic when recompiling libraries due to function overloads 
- Added test with ELM and overloaded functions
=> Issue with namespace info being lost when Libraries are recompiled 

evaluator.library/src/main/java/org/opencds/cqf/cql/evaluator/library/EvaluationSettings.java
* Add a local cache when a global one is not set
=> Use an initial cache for evaluation settings

evaluator.questionnaire/src/main/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/ItemValueTransformer.java, evaluator.questionnaire/src/main/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/QuestionnaireProcessor.java, evaluator.questionnaire/src/main/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/generator/nestedquestionnaireitem/ElementHasCqfExpression.java, evaluator.questionnaire/src/main/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/generator/nestedquestionnaireitem/ElementHasDefaultValue.java, evaluator.questionnaire/src/main/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/generator/nestedquestionnaireitem/NestedQuestionnaireItemService.java, evaluator.questionnaire/src/main/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/generator/nestedquestionnaireitem/QuestionnaireTypeIsChoice.java, evaluator.questionnaire/src/main/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/generator/questionnaireitem/QuestionnaireItemGenerator.java, evaluator.questionnaire/src/test/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/generator/nestedquestionnaireitem/ElementHasCqfExpressionTest.java, evaluator.questionnaire/src/test/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/generator/nestedquestionnaireitem/ElementHasDefaultValueTest.java, evaluator.questionnaire/src/test/java/org/opencds/cqf/cql/evaluator/questionnaire/r4/generator/nestedquestionnaireitem/NestedQuestionnaireItemServiceTest.java
Questionnaire.initial.value[x] does not allow a CodeableConcept, only a Coding.  During Questionnaire item generation, when the result of an initial value is a CodeableConcept, we now transform it to a Coding.
=> Add support for transforming the value when setting initial on generated questionnaire items

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureService.java
Related Issue: https://github.com/alphora/dqm-platform/issues/362
Allow for subjects to be passed into processor to avoid redundant calls of getSubjects
=> isolate getsubjects method in Measure Processor

cqf-fhir-cql/pom.xml, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/CqfExpression.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/LibraryConstructor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/MeasureOperationParameterConverter.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/dstu3/Dstu3MeasureProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/plandefinition/OperationParametersParser.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/dstu3/generator/nestedquestionnaireitem/NestedQuestionnaireItemServiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/dstu3/generator/nestedquestionnaireitem/QuestionnaireTypeIsChoiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/dstu3/generator/questionnaireitem/QuestionnaireItemGeneratorTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/dstu3/generator/questionnaireitem/QuestionnaireItemServiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/dstu3/helpers/TestingHelper.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r4/generator/nestedquestionnaireitem/ElementHasCqfExpressionTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r4/generator/nestedquestionnaireitem/NestedQuestionnaireItemServiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r4/generator/nestedquestionnaireitem/QuestionnaireTypeIsChoiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r4/generator/questionnaireitem/QuestionnaireItemGeneratorTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r4/generator/questionnaireitem/QuestionnaireItemServiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r4/helpers/TestingHelper.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r5/generator/nestedquestionnaireitem/ElementHasCqfExpressionTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r5/generator/nestedquestionnaireitem/NestedQuestionnaireItemServiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r5/generator/nestedquestionnaireitem/QuestionnaireTypeIsChoiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r5/generator/questionnaireitem/QuestionnaireItemGeneratorTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r5/generator/questionnaireitem/QuestionnaireItemServiceTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/r5/helpers/TestingHelper.java, pom.xml
* remove use of Inject annotations
* change JavaX annotations to Jakarta for Nonnull
* used at compile time only, so no implications for runtime.
=> Remove use of Inject annotations, swap to jakarta for nonnull

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/BaseQuestionnaireProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/dstu3/generator/questionnaireitem/QuestionnaireItemService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/r4/generator/questionnaireitem/QuestionnaireItemService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/r5/generator/questionnaireitem/QuestionnaireItemService.java
Add the CPG Feature expression extension to the list of extensions that are copied from the action.input to the questionnaire item when generating items from the input profile.
=> Add CPG Feature expression to generated items

.vscode/settings.json, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/engine/terminology/RepositoryTerminologyProvider.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/engine/terminology/RepositoryTerminologyProviderTest.java, cqf-fhir-cql/src/test/resources/org/opencds/cqf/fhir/cql/engine/terminology/MissingCodeValueSet.json, cqf-fhir-cql/src/test/resources/org/opencds/cqf/fhir/cql/engine/terminology/MissingSystemValueSet.json, cqf-fhir-cql/src/test/resources/org/opencds/cqf/fhir/cql/engine/terminology/ValidValueSet.json
* Fixes null pointer exceptions when codes are incompletely specified
* Fixes null pointer exceptions when valuesets are incompletely specified
* The above is accomplished by ignoring (i.e. filtering out) partially specified codes
=> Fixes for malformed codes and valuesets

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaireresponse/extract/ProcessDefinitionItem.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaireresponse/QuestionnaireResponseProcessorTests.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/questionnaireresponse/r4/tests/QuestionnaireResponse-TherapyMonitoringRecommendation.json
Added logic to the $extract operation to determine if type transformation needs to occur when setting values on the extracted resource from the QuestionnaireResponse answerValues and if needed perform that transformation.
=> Fix $extract bug with answerValue transform

cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/Engines.java
Calling `Engines.forRepository(repository)` fails with an exception:
```
Caused by: java.lang.UnsupportedOperationException: null
at java.base/java.util.AbstractList.add(AbstractList.java:155) ~[na:na]
at java.base/java.util.AbstractList.add(AbstractList.java:113) ~[na:na]
at org.opencds.cqf.fhir.cql.Engines.buildEnvironment(Engines.java:112) ~[cqf-fhir-cql-3.0.0.jar:3.0.0]
at org.opencds.cqf.fhir.cql.Engines.forRepository(Engines.java:64) ~[cqf-fhir-cql-3.0.0.jar:3.0.0]
at org.opencds.cqf.fhir.cql.Engines.forRepository(Engines.java:53) ~[cqf-fhir-cql-3.0.0.jar:3.0.0]
at org.opencds.cqf.fhir.cql.Engines.forRepository(Engines.java:49) ~[cqf-fhir-cql-3.0.0.jar:3.0.0]
at gov.ri.reporting.web.SampleController.<init>(SampleController.java:41) ~[classes/:na]
at …
```
=> Fix UnsupportedOperationException

cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/Engines.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/populate/PopulateProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/populate/ProcessItemWithContext.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/QuestionnaireProcessorTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/TestQuestionnaire.java
When populating an item with the SDC Questionnaire Item Population Context extension no QuestionnaireResponse Author extension was being added denoting that the item had been answered by CQL Evaluation.
=> Add missing author extension for items with Population Context Extension

cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/LibraryConstructor.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/VersionedIdentifiers.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/VersionedIdentifiersTests.java
Change VersionedIdentifiers helper method to allow for Dstu3 references which may be just resourceType/id due to how HAPI stores Dstu3 PlanDefinition resources.
Closes #445
=> Resolve issue with Dstu3 Library identifier

cqf-fhir-cql/pom.xml, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/helper/SubjectContext.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CollectDataService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4DataRequirementsService.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/CollectData.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/CollectDataTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/DataRequirements.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/DataRequirementsTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/library/MinimalProportionResourceBasisSingleGroupCanonical.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/library/MinimalProportionResourceBasisSingleGroupCanonical2.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalCohortBooleanBasisSingleGroupCanonical.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalCohortBooleanBasisSingleGroup_badLibraryUrl.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/patient/male-2022.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/practitioner/practitioner-empy.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/practitioner/practitioner-tester.json
Migrating cqf-ruler operations into CR
Closes #444
=> 444 migrate collect data and data req operations

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/activitydefinition/apply/ApplyRequest.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/inputparameters/IInputParameterResolver.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/plandefinition/apply/ApplyRequest.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/QuestionnaireProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/populate/PopulateRequest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/activitydefinition/RequestResourceResolver.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/common/DynamicValueProcessorTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/helpers/RequestHelpers.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/plandefinition/apply/ApplyRequestTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/plandefinition/apply/ProcessActionTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/plandefinition/apply/ProcessDefinitionTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/plandefinition/apply/ProcessGoalTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/plandefinition/apply/ProcessRequestTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/TestQuestionnaire.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/populate/PopulateProcessorTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/populate/ProcessItemTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/populate/ProcessResponseItemTests.java
Add the InputParameterResolver to the PopulateRequest which resolves the input parameters to resources to allow them to be referenced within an expression, e.g. %subject.id
=> Add input parameter resolution to $populate operation

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/client/Clients.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/client/ClientsTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/KnowledgeArtifactPackageVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/KnowledgeArtifactPackageVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/KnowledgeArtifactPackageVisitorTests.java
Also includes spotless changes that were not detected in PRs from forks.
=> Fix Additional Request Headers Auth Registration and Add Test

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/dstu3/KnowledgeArtifactPackageVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/r4/KnowledgeArtifactPackageVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/r5/KnowledgeArtifactPackageVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/KnowledgeArtifactPackageVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/KnowledgeArtifactPackageVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/KnowledgeArtifactPackageVisitorTests.java
We have elected to rethrow exceptions encountered during Value Set expansion. This will cause operations which include expansion to fail if a single value set cannot be expanded.
=> Rethrow exceptions encountered during value set expansion

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/dstu3/KnowledgeArtifactPackageVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/r4/KnowledgeArtifactPackageVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/r5/KnowledgeArtifactPackageVisitor.java
=>  NOJIRA-public_expand_value_set

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalProportionBooleanBasisSingleGroupGroupScoringDef.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/organization/alphora-author.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/organization/alphora.json
=> 466 bug fix for group level scoring def, and concurrent mod exception

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/KnowledgeArtifactDraftVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/KnowledgeArtifactReleaseVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/KnowledgeArtifactDraftVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/KnowledgeArtifactReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/KnowledgeArtifactDraftVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/KnowledgeArtifactReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/KnowledgeArtifactDraftVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/KnowledgeArtifactReleaseVisitorTests.java, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/dstu3/Bundle-ersd-example-naive.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/dstu3/Bundle-ersd-example.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/dstu3/Library-version-conflict.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r4/Bundle-ersd-example-naive.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r4/Bundle-ersd-example.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r4/Library-version-conflict.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r5/Bundle-ersd-example-naive.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r5/Bundle-ersd-example.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r5/Library-version-conflict.json
remove revision from release  version to leave 3 part version
=> APHL-1013-revert_3part_version

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MultiMeasureService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/utils/R4MeasureServiceUtils.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MultiMeasure.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MultiMeasureServiceTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalProportionNoBasisSingleGroup.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/group/group-patients-1.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/group/group-practitioners-1.json
new feature expansion to multi-measure evaluate request:
- individual measureReport mode, that allows for individual MeasureReport creation for each subject identified via the subject parameter
- consolidated practitioner parameter capability into subject parameter, for a single population parameter. This allows for simplified explanation and use of api
- canonicalUrl Measure parameter that allows for both measureId and measureUrl to be used to identify the Measure to use.
- stubbed in identifier search logic for measures once implemented
closes https://github.com/cqframework/clinical-reasoning/issues/492
=> multi-measure feature enhancements

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/ExpandHelper.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/client/TerminologyServerClient.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/PackageVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/ReleaseVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/VisitorHelper.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/ExpandHelperTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/client/TerminologyServerClientTest.java
- refactor out "tryGetLatest"
- update expandHelper to pull from tx server or repository as applicable
- boolean bug in expansion handling
=> updates to package and expand:

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/ExpandHelper.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/ExpandHelperTest.java
closes [APHL-1121]
[APHL-1121]: https://alphora.atlassian.net/browse/APHL-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't throw an error if a grouper encounters an empty leaf

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/Constants.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/ExpandHelper.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/adapter/dstu3/LibraryAdapter.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/adapter/r4/LibraryAdapter.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/adapter/r5/LibraryAdapter.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/ReleaseVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/ExpandHelperTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/ReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/ReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/ReleaseVisitorTests.java
[APHL-1067] filter out unsupported Expansion Parameters
[APHL-1067]: https://alphora.atlassian.net/browse/APHL-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Filter out unsupported Expansion Parameters and Respect `canonical-version` and `system-version` when Releasing

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsProcessor.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsTest.java
=> measure basis compliance rule

cqf-fhir-api/pom.xml, cqf-fhir-benchmark/pom.xml, cqf-fhir-bom/pom.xml, cqf-fhir-cql/pom.xml, cqf-fhir-cr-cli/pom.xml, cqf-fhir-cr-spring/pom.xml, cqf-fhir-cr/pom.xml, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/dstu3/Dstu3MeasureEvaluationTest.java, cqf-fhir-jackson/pom.xml, cqf-fhir-jaxb/pom.xml, cqf-fhir-test/pom.xml, cqf-fhir-utility/pom.xml, docs/pom.xml, pom.xml
* Update to version 3.12.0
* Update to latest HAPI/CQL
* Fix failing tests
* The latest CQL compile is more strict about function resolution. This breaks the implicit conversions specified in older versions of FHIRHelpers used for FHIR DSTU3 support.
=> Rev to latest CQL/HAPI

.vscode/settings.json, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/repository/InMemoryFhirRepository.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/ApproveVisitorTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/DraftVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/PackageVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/ReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/ApproveVisitorTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/DraftVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/PackageVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/ReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/RetireVisitorTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/WithdrawVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/ApproveVisitorTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/DraftVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/PackageVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/ReleaseVisitorTests.java
* Move the transaction stub implementation into transaction
* This allows the InMemoryRepository to be used as a "fake" rather than a "mock"
* Update all tests using that stub
=> Move transactionStub to transaction implementation for repository

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/DataRequirementsVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/adapter/KnowledgeArtifactAdapter.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/PackageVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/ReleaseVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/ReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/ReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/ReleaseVisitorTests.java
Added a check to prevent the same artifact from being iterated through multiple times in the ReleaseVisitor if that artifact is referenced by multiple artifacts.
=> Fix multiple iterations of an artifact in ReleaseVisitor

cqf-fhir-benchmark/src/test/java/org/opencds/cqf/fhir/benchmark/Measures.java, cqf-fhir-benchmark/src/test/java/org/opencds/cqf/fhir/benchmark/MeasuresAdditionalData.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/Engines.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/EvaluationSettings.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/LibraryEngine.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/LibraryEngineTests.java, cqf-fhir-cr-cli/src/main/java/org/opencds/cqf/fhir/cr/cli/command/CqlCommand.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureProcessorEvaluateTest.java
* Makes EvaluationSettings (shallowly) immutable
* Adds an EvaluationSettings.Builder to construct/clone EvaluationSettings instances
* Move NpmProcessor to EvaluationSettings, remove overloads for constructing with NpmProcessor
* Update LibraryEngine to use request-specific EvaluationSettings
* Update tests
=> Create an EvaluationSettingsBuilder

.github/workflows/build.yml, .github/workflows/check-pr.yaml, cqf-fhir-cql/pom.xml, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/Engines.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/LibraryEngine.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/EnginesTest.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/ResourceDirectoryResolver.java, cqf-fhir-cql/src/test/resources/org/opencds/cqf/fhir/cql/npm/ig.ini, cqf-fhir-cql/src/test/resources/org/opencds/cqf/fhir/cql/npm/ig.json, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/cpg/r4/R4CqlExecutionService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/cpg/r4/R4LibraryEvaluationService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/dstu3/Dstu3MeasureProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureProcessor.java
* Rename overloads and reorder parameters so that they are consistent across each
* Refactor NPM logic so that it's consolidated in one place
* Refactor LibrarySourceProvider creation so that it's (mostly) in one place
* Fix duplicate FHIRLibrarySourceProvider bug
=> Refactor "Engines" class

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/ExpandHelper.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/DeleteVisitor.java
Delete Operation must also delete the Basic resources which represent the comments/approvals of the specified artifact
Spotless also formatted unrelated file.
=> Update Delete operation to include deletion of Artifact Comments

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/plandefinition/apply/ApplyProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/questionnaire/populate/ProcessItemWithContext.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/questionnaire/populate/ProcessItemWithContextTests.java
When using the item population context extension, a responseItem should now always be returned even when there is no data to populate an answer.
=> Fix $populate issue with missing responseItems for a null population context

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapStatusEvaluator.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalProportionDenominatorExclusion.json
=> fix not-applicable status for care-gaps

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/DraftVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/DraftVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/DraftVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/DraftVisitorTests.java, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/dstu3/Bundle-ersd-example.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r4/Bundle-ersd-example.json, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r5/Bundle-ersd-example.json
When creating a draft of a program, the newly-created drafts owned resource artifacts still have a releaseLabel & releaseDescription extensions and they should not - they’re drafts and haven’t yet been released. 
This PR:
-removes 'releaseLabel' & 'releaseDescription' extensions from owned resources when creating a new Draft Program 
-update test data and assertions to reflect and validate
=> Remove Release extensions when creating a Draft of a Program

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/ExpandHelper.java
When exporting a Program in VSM, we are encountering the following error:
`java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "authoritativeSourceUrl" is null
at org.opencds.cqf.fhir.utility.ExpandHelper.expandValueSet(ExpandHelper.java:76)`
This change adds a null check for the authoritativeSourceUrl to to handle cases where the authoritativeSourceUrl is null but does not return true in these cases.
=> Add null check to authoritativeSourceUrl

.github/workflows/codeql.yml, .mvn/wrapper/maven-wrapper.properties, cqf-fhir-cr-cli/pom.xml, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/Measure.java, pom.xml
* Update Maven to 3.3.9
* Fix CodeQL scanning (default scanning is only compatible with Java 11, so switched to advanced mode)
* Update latest versions of Junit and Error Prone
* Update Maven build plugins to latest versions
=> Dependency updates

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/ReleaseVisitor.java
[APHL-1288]
[APHL-1288]: https://alphora.atlassian.net/browse/APHL-1288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Skip duplicated URLs when gathering deps

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4SubmitDataService.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4SubmitDataServiceTest.java
- Write new test
- Tweak javadocs
Closes:  https://github.com/cqframework/clinical-reasoning/issues/601
=> Add tests for R4SubmitDataService and tweak docs for class itself.

.vscode/settings.json, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasureEvaluator.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasurePopulationType.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/constant/MeasureConstants.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/dstu3/Dstu3MeasureDefBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/dstu3/Dstu3MeasureReportBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureDefBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureReportBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureReportScorer.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureScoringTypePopulations.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoring/MeasureReports/measurereport-fhir347.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoring/MeasureReports/measurereport-multirate-nopopid.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoring/MeasureReports/measurereport-multirate-zeroden.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoring/MeasureReports/measurereport-primarycariespreventionasofferedbypcpincludingdentistfhir.json
- Delete total numerator and total denominator extension URLs from MeasureConstants
- Delete total numerator and total denominator from MeasurePopulationType and all downstream enums
- Delete all code that writes to the above extensions
- Change measure scoring code to read directly from the numerator and denominator populations
- Remove conditional logic that subtracts 2 from expected population counts.
- Delete all other code that does anything with total denominator and numerator
- Remove total extensions from all JSON test files.
Closes https://github.com/cqframework/clinical-reasoning/issues/602
=> Eliminate total denominator and total numerator extensions as well as all related code in favour of denominator and numerator

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasureEvalType.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureDefBuilderTest.java
- Unit test covering various scenarios for building StratifierDef in R4MeasureDefBuilder
- Make MeasureEvalType throw InvalidRequestException upon an invalid measure eval type
Closes https://github.com/cqframework/clinical-reasoning/issues/608
=> New unit tests for building StratifierDef in R4MeasureDefBuilder

cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/cpg/r4/LibraryEvaluationServiceTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/cpg/r4/libraryeval/cql/ReturnedSets.cql, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/cpg/r4/libraryeval/resources/library/ReturnedSets.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/cpg/r4/libraryeval/tests/encounter/SimpleEncounter.json
- Test only change
- Add new test to prove that library evaluation with parameters and returned sets works.
=> Add new test to prove that library evaluation with parameters and returned sets works.

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/PackageVisitor.java
[APHL-1352] - In eCR we need to do some post-processing to the packaged bundle before returning it to the customer but don't want to duplicate the paging code. It would be great if we could just re-use from the visitor.
[APHL-1352]: https://alphora.atlassian.net/browse/APHL-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make package paging public

cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/engine/retrieve/BaseRetrieveProvider.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/engine/retrieve/BaseRetrieveProviderTests.java
When a CQL retrieve is filtered by a template and the engine is set to use search parameters for filtering the `_profile` searchParam was always being given a ReferenceParam.  This parameter type was changed in R5 to be a ReferenceParam but is still a UriParam in R4 and previous versions.  This fix checks the version of the FhirContext being used and sets the parameter type accordingly.
=> Fix wrong parameter type used when filtering CQL retrieves by template

cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/config/CrCdsHooksConfig.java
Qualify the name of the CDS Hooks ObjectMapper bean for use in CrCdsHooksConfig in case the downstream project uses multiple ObjectMapper beans.
=> Add qualifier for correct object mapper in CrCdsHooksConfig

cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/LibraryEngine.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/engine/retrieve/BaseRetrieveProvider.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/engine/retrieve/RepositoryRetrieveProvider.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/engine/retrieve/BaseRetrieveProviderTests.java, cqf-fhir-cr-hapi/src/test/java/org/opencds/cqf/fhir/cr/hapi/r4/PlanDefinitionOperationsProviderIT.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/cpg/r4/R4CqlExecutionService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/cpg/r4/R4LibraryEvaluationService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/library/evaluate/EvaluateProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasureEvaluator.java
Change to the BaseRetrieveProvider to not add a profile search parameter when using search parameters for retrieves and a template id is provided that is for a default FHIR profile.
Added rawParameters argument for raw CQL parameters to Library evaluate calls (previously was only passed when evaluating a CQL expression).
=> Fix default profile search param

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/constant/MeasureConstants.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/ReleaseVisitor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/r4/ReleaseVisitor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/r5/ReleaseVisitor.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/visitor/r4/ReleaseVisitorTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/visitor/r5/ReleaseVisitorTests.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/visitor/r5/Bundle-ecqm-qicore-2024-simplified.json, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/Constants.java
Update $release operation to gather any direct-reference codes referenced by component measures and add them to the manifest, using the directReferenceCode extension slice on the root of the release manifest.
Functionality handles STU4/STU5+, works with cqfm-directReferenceCode (STU4) and cqf-directReferenceCode (STU5) in the Measure source, output is always cqf-directReferenceCode extensions in the Manifest because cqfm-directReferenceCode isn't allowed in a CRMIManifest.
=> Add direct reference codes to manifest during $release

cqf-fhir-cr-cli/src/main/java/org/opencds/cqf/fhir/cr/cli/command/CqlCommand.java
This removes deprecated ILoggingService usage in favour of the now available class that replaces it.
=> Remove deprecated ILoggingService

cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MultiMeasure.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MultiMeasureServiceTest.java
- Improve MultiMeasureServiceTest to assert partial errors on invalid Encounter Interval in addition to the other successful measure reports.
- Tweak MultiMeasure to retrieve a MeasureReport by subject + measure URL as well as resolving some "class exposed outside of scope" warnings.
=> Improve MultiMeasureServiceTest to assert partial errors on invalid Encounter Interval

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/CompositeEvaluationResultsPerMeasure.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/common/CompositeEvaluationResultsPerMeasureTest.java
CompositeEvaluationResultsPerMeasure class requires additional methods to allow extraction of built objects within it for potential use in different downstream applications that can leverage the produced data.
As it stands the Class allows building of results and convenient portability of results for methods that want to consume data per Measure, but lack access to full `Map<IIdType, Map<String, EvaluationResult>> resultsPerMeasure` or `Map<IIdType, List<String>> errorsPerMeasure`
This PR allows for access to those built objects for multiple downstream use cases outside of Measure evaluation
=> Compositeevalresults add getters

cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/config/r4/CrR4Config.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/r4/IApproveServiceFactory.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/r4/crmi/ApproveProvider.java, cqf-fhir-cr-hapi/src/test/java/org/opencds/cqf/fhir/cr/hapi/r4/ApproveProviderIT.java, cqf-fhir-cr-hapi/src/test/resources/ersd-active-library-example.json, cqf-fhir-cr-hapi/src/test/resources/practitioner-example-for-refs.json, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/crmi/R4ApproveService.java
- Added $approve operation provider and service
- Added the operation to the R4 CR config
- Added documentation
- TODO - Add tests, add operation name and operation definition URL to ProviderConstants in HAPI (or some other constants class), and run integration testing with eCR components
Motivation for this enhancement is tracked [here](https://github.com/DBCG/aphl-vsm/issues/526)
=> CRMI Approve Operation (R4)

cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/r4/measure/MeasureOperationsProvider.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsBundleBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureEvaluatorMultiple.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MultiMeasureService.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MultiMeasure.java
Change the return type of the Measure/$evaluate operation to match the DEQM STU5 publication and always return a Parameters resource with a Bundle for each Measure/Subject being evaluated.
#682
=> Change return type of $evaluate operation to a Parameters resource
