cqframework/clinical-reasoning

pom.xml
* Update to translator 1.4.9-SNAPSHOT
=> Rev to new version of translator

service/src/main/java/org/opencds/cqf/cql/service/factory/DefaultDataProviderFactory.java, service/src/main/java/org/opencds/cqf/cql/service/serialization/EvaluationResultsSerializer.java
Same as the other but for data provider.
=> Added data provider for fhir 401

evaluator.dagger/src/test/java/org/opencds/cqf/cql/evaluator/dagger/library/LibraryModuleTests.java, pom.xml
This PR was created automatically based on the maintenance script in this project.
=> Autogenerated maintenance PR

evaluator.activitydefinition/src/main/java/org/opencds/cqf/cql/evaluator/activitydefinition/r4/ActivityDefinitionProcessor.java, evaluator.library/src/main/java/org/opencds/cqf/cql/evaluator/library/LibraryProcessor.java
* Updates to ActivityDefinitionApplyFhirPath
=> Activity definition apply fhir path

.gitignore, evaluator.engine/src/main/java/org/opencds/cqf/cql/evaluator/engine/util/CodeUtil.java, evaluator.engine/src/test/java/org/opencds/cqf/cql/evaluator/engine/util/CodeUtilTests.java, pom.xml
* Add support for getting codes from Enumeration
* Fixed accidentally removed CodeUtilTests
* Update to HAPI 5.4.1
=> Fix codeutils enumeration support

evaluator.engine/src/main/java/org/opencds/cqf/cql/evaluator/engine/model/CachingModelResolverDecorator.java, evaluator.engine/src/main/java/org/opencds/cqf/cql/evaluator/engine/retrieve/BundleRetrieveProvider.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/MeasureProcessor.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureEvaluation.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/stu3/Stu3MeasureEvaluation.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureEvaluationTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/stu3/Stu3MeasureEvaluationTest.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/MeasureEvaluation.java, pom.xml
* WIP on Measure evaluation refactoring
* Makes Measure eval more "self-contained" in that it only needs a Context and a Measure
=> Refactoring to make measure eval more self-contained

.gitignore, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/BaseMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/BloodPressureMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/CohortMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/ContinuousVariableMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/DaVinciExtensionMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/DiabetesMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/EncounterBasisMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/MultipleRateMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureEvaluationTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/SimpleMeasureProcessorTest.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/StratifierMeasureProcessorTest.java, pom.xml
* Update to CQL Engine 1.5.2
* Fix multithreaded tests crashing
=> Update to CQL Engine 1.5.2

evaluator.engine/src/main/java/org/opencds/cqf/cql/evaluator/engine/elm/LibraryMapper.java, evaluator.engine/src/main/java/org/opencds/cqf/cql/evaluator/engine/util/TranslatorOptionsUtil.java, evaluator.engine/src/test/java/org/opencds/cqf/cql/evaluator/engine/elm/MapperCodeGen.java, evaluator.engine/src/test/java/org/opencds/cqf/cql/evaluator/engine/util/TranslatorOptionsUtilTests.java, evaluator.engine/src/test/resources/org/opencds/cqf/cql/evaluator/engine/util/AdultOutpatientEncounters_FHIR4-2.0.000.xml, evaluator.engine/src/test/resources/org/opencds/cqf/cql/evaluator/engine/util/LibraryTestMappedOptions.cql, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureProcessor.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/BaseMeasureProcessorTest.java
This PR fixes some issues found in regression
* Performance issues due to cache misses on Libraries resolved
* A few hackarounds added to address some missing classes in the cql-engine.
=> Feature 1.3.0 prep

evaluator.activitydefinition/pom.xml, evaluator.builder/pom.xml, evaluator.cli/pom.xml, evaluator.content-test/pom.xml, evaluator.cql2elm/pom.xml, evaluator.dagger/pom.xml, evaluator.engine/pom.xml, evaluator.expression/pom.xml, evaluator.fhir/pom.xml, evaluator.library/pom.xml, evaluator.measure-hapi/pom.xml, evaluator.measure/pom.xml, evaluator.spring/pom.xml, evaluator/pom.xml, pom.xml
* Added Measure module
* Additionally, implemented Measure stratification
* Add FhirPath/CQL Expression module
* Fixes for in-memory Terminology
* Fixes for Library caching
This release is shipping due to project deadlines, but it has a couple of known issues
1. Not really pleased with the way the Platform APIs came together and implementation experience has suggested a different approach is needed. Going to solicit community feedback for the next round - #57 
2. The Fhir MeasureReportBuilders duplicate a lot of code, and are not model-independent, which is a step backwards. This will be addressed in a future release - #56
=> Proposed 1.3.0 Release

evaluator.activitydefinition/src/test/java/org/opencds/cqf/cql/evaluator/activitydefinition/r4/ActivityDefinitionProcessorTests.java, evaluator.builder/src/main/java/org/opencds/cqf/cql/evaluator/builder/CqlEvaluatorBuilder.java, evaluator.dagger/src/main/java/org/opencds/cqf/cql/evaluator/dagger/builder/BuilderModule.java, evaluator.expression/src/main/java/org/opencds/cqf/cql/evaluator/expression/ExpressionEvaluator.java, evaluator.expression/src/test/java/org/opencds/cqf/cql/evaluator/expression/ExpressionEvaluatorTest.java, evaluator.library/src/main/java/org/opencds/cqf/cql/evaluator/library/CqlFhirParametersConverter.java, evaluator.library/src/main/java/org/opencds/cqf/cql/evaluator/library/LibraryProcessor.java, evaluator.library/src/test/java/org/opencds/cqf/cql/evaluator/library/LibraryProcessorTests.java, evaluator.measure/src/test/java/org/opencds/cqf/cql/evaluator/measure/helper/DateHelperTest.java
* Add no-op provider support for expression evaluation
* Tests for same
=> Add no op support for expressions

evaluator.plandefinition/src/test/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessorTests.java, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/hello-world-patient-view-bundle.json, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/helloworld-careplan.json, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/helloworldpatientdata.json
taking unit test from pd-apply project and adding to plandefinition evaluator tests
=> unit test plandefiniion apply on hello world plan defintion

evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/engine/terminology/BundleTerminologyProvider.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/engine/util/ValueSetUtil.java, evaluator.fhir/src/test/java/org/opencds/cqf/cql/evaluator/engine/terminology/BundleTerminologyProviderTests.java, evaluator.fhir/src/test/resources/org/opencds/cqf/cql/evaluator/engine/util/r4/TestBundleValueSetsTwo.json, evaluator.fhir/src/test/resources/org/opencds/cqf/cql/evaluator/engine/util/r4/TestExpansionLogicBundle.json, evaluator.fhir/src/test/resources/org/opencds/cqf/cql/evaluator/engine/util/r4/TestNaiveExpansionBundle.json, pom.xml
Added check for unexpanded valuesets with expansion logic and throw error
Added tests for change
=> Fix Unresolved ValueSet Expansion

evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/dstu3/Dstu3MeasureReportBuilder.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureReportBuilder.java, evaluator.measure-hapi/src/test/java/org/opencds/cqf/cql/evaluator/measure/r4/MeasureProcessorSdeAddCriteriaExtensionTest.java
The extension look like below:
=> drop extension list

evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureDefBuilder.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureReportBuilder.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/MeasureConstants.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/SdeDef.java
Updates the extension to have sde criteria. 
Duplicate check and merge is tech debt.
=> Sde design update

evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureReportBuilder.java
=> Update SDE contained reference to be internal

evaluator.activitydefinition/pom.xml, evaluator.builder/pom.xml, evaluator.cli/pom.xml, evaluator.content-test/pom.xml, evaluator.dagger/pom.xml, evaluator.expression/pom.xml, evaluator.fhir/pom.xml, evaluator.jackson-deps/pom.xml, evaluator.jaxb-deps/pom.xml, evaluator.library/pom.xml, evaluator.measure-hapi/pom.xml, evaluator.measure/pom.xml, evaluator.plandefinition/pom.xml, evaluator.spring/pom.xml, evaluator/pom.xml, pom.xml
=> v2.0.0 release

evaluator.fhir/pom.xml
These are ~50MB each of xml files.
=> Removing heavy resources from the main fhir lib

evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/engine/retrieve/BundleRetrieveProvider.java
Update BundleRetrieveProvider.java to use Java streams to filter resources. This results in cleaner, more concise code as well as better performance as a new ArrayList is not being created for each filter stage. This change should not result in any visible change in behavior.
=> Update BundleRetrieveProvider.java to use streams

evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/behavior/FhirContextUser.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/behavior/IdCreator.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/behavior/ResourceCreator.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/BackboneElementBuilder.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/BundleBuilder.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/CodeableConceptSettings.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/CodingSettings.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/CompositionBuilder.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/CompositionSectionComponentBuilder.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/DetectedIssueBuilder.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/DomainResourceBuilder.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/NarrativeSettings.java, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/fhir/builder/ResourceBuilder.java, pom.xml
Integrating care-gaps functionality and pulled common code in here.
=> Integrating care-gaps common code.

evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/engine/retrieve/BundleRetrieveProvider.java
* The BundleUtil.toListOfResources call is expensive. This PR does it once eagerly instead of many times lazily.
=> Eagerly cache resource in Bundle provider

.vscode/settings.json, evaluator.cli/src/test/java/org/opencds/cqf/cql/evaluator/cli/CliTest.java, evaluator.fhir-npm/src/main/java/org/opencds/cqf/cql/evaluator/fhir/npm/LoggerAdapter.java, evaluator.fhir/pom.xml, evaluator.fhir/src/main/java/org/opencds/cqf/cql/evaluator/engine/retrieve/BundleRetrieveProvider.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/dstu3/Dstu3MeasureReportBuilder.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureReportBuilder.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/CriteriaResult.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/MeasureEvaluator.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/PopulationDef.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/SdeDef.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/StratifierComponentDef.java, evaluator.measure/src/main/java/org/opencds/cqf/cql/evaluator/measure/common/StratifierDef.java, evaluator/pom.xml, pom.xml
* Use a set for tracking evaluated resources
=> Use set for evaluated resources

evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/dstu3/PlanDefinitionProcessor.java, evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessor.java, evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/r5/PlanDefinitionProcessor.java, evaluator.plandefinition/src/test/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessorTests.java, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-dak/content/Library-ANCContactDataElements.json, evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/anc-dak/cql/ANCContactDataElements.cql
- Updated test case to latest 
- Now including params from apply operation request into action parameter resolution
=> ANCDT17 Test Case

.vscode/settings.json, evaluator.questionnaireresponse/src/main/java/org/opencds/cqf/cql/evaluator/questionnaireresponse/BaseQuestionnaireResponseProcessor.java, evaluator.questionnaireresponse/src/main/java/org/opencds/cqf/cql/evaluator/questionnaireresponse/dstu3/QuestionnaireResponseProcessor.java, evaluator.questionnaireresponse/src/main/java/org/opencds/cqf/cql/evaluator/questionnaireresponse/r4/QuestionnaireResponseProcessor.java, evaluator.questionnaireresponse/src/main/java/org/opencds/cqf/cql/evaluator/questionnaireresponse/r5/QuestionnaireResponseProcessor.java
Add id parameter to extract to allow for extraction of resources in the repository.
=> Add id parameter to extract

evaluator.measure-hapi/pom.xml, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/MeasureEvaluationOptions.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/dstu3/Dstu3MeasureProcessor.java, evaluator.measure-hapi/src/main/java/org/opencds/cqf/cql/evaluator/measure/r4/R4MeasureProcessor.java
In order to fix security context dropping when in threaded mode, added delegation of security context to executor
=> Async security context

cqf-fhir-benchmark/src/test/java/org/opencds/cqf/fhir/benchmark/BenchmarksIT.java, cqf-fhir-benchmark/src/test/java/org/opencds/cqf/fhir/benchmark/Measures.java, cqf-fhir-benchmark/src/test/java/org/opencds/cqf/fhir/benchmark/PlanDefinitions.java, cqf-fhir-benchmark/src/test/java/org/opencds/cqf/fhir/benchmark/Questionnaires.java, evaluator.measure-hapi/src/test/resources/org/opencds/cqf/cql/evaluator/measure/r4/CaseRepresentation101/vocabulary/valueset/encounter-discharge-disposition.json, evaluator.measure-hapi/src/test/resources/org/opencds/cqf/cql/evaluator/measure/r4/InitialInpatientPopulation/vocabulary/valueset/encounter-discharge-disposition.json, evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/dstu3/PlanDefinitionProcessor.java, evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessor.java, evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/r5/PlanDefinitionProcessor.java
=> More benchmark cleanup

cqf-fhir/pom.xml, pom.xml
=> Update to use CQL 3.0.0

.github/workflows/check-pr.yaml, .github/workflows/spotless.yml, cqf-fhir-api/pom.xml, cqf-fhir-benchmark/pom.xml, cqf-fhir-bom/pom.xml, cqf-fhir-cql/pom.xml, cqf-fhir-cr-cli/pom.xml, cqf-fhir-cr-spring/pom.xml, cqf-fhir-cr/pom.xml, cqf-fhir-jackson/pom.xml, cqf-fhir-jaxb/pom.xml, cqf-fhir-test/pom.xml, cqf-fhir-utility/pom.xml, docs/pom.xml, pom.xml
=> Rev to version 3.0.0-PRE6

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/dstu3/Dstu3MeasureProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureProcessor.java
Fixes https://github.com/cqframework/clinical-reasoning/issues/358
=> Fixes crash on measure evaluate when subjectIds is null

.github/workflows/check-pr.yaml, .vscode/settings.json, cqf-fhir-api/pom.xml, cqf-fhir-benchmark/pom.xml, cqf-fhir-bom/pom.xml, cqf-fhir-cql/pom.xml, cqf-fhir-cr-cli/pom.xml, cqf-fhir-cr-spring/pom.xml, cqf-fhir-cr/pom.xml, cqf-fhir-jackson/pom.xml, cqf-fhir-jaxb/pom.xml, cqf-fhir-test/pom.xml, cqf-fhir-utility/pom.xml, docs/pom.xml, pom.xml
* Version 3.0.0-PRE9
* Update HAPI/CQL versions
* Fix test script publication
=> Update versions and fix build / test publication

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java
closes #373 
missing workflow for "not-applicable" care-gap scenario
=> add care-gaps not-applicable status workflow

cqf-fhir-api/pom.xml, cqf-fhir-benchmark/pom.xml, cqf-fhir-bom/pom.xml, cqf-fhir-cql/pom.xml, cqf-fhir-cr-cli/pom.xml, cqf-fhir-cr-spring/pom.xml, cqf-fhir-cr/pom.xml, cqf-fhir-jackson/pom.xml, cqf-fhir-jaxb/pom.xml, cqf-fhir-test/pom.xml, cqf-fhir-utility/pom.xml, docs/pom.xml, pom.xml
* Update to latest non-Javax CQL releases
* Remove dependencies that  are no longer needed
* Update version number
=> Version 3.0.0-PRE10

.github/workflows/build.yml, .github/workflows/check-pr.yaml
* Build with Java 21
* Update github actions version.
=> Update github build actions to use Java 21

cqf-fhir-api/pom.xml, cqf-fhir-benchmark/pom.xml, cqf-fhir-bom/pom.xml, cqf-fhir-cql/pom.xml, cqf-fhir-cr-cli/pom.xml, cqf-fhir-cr-spring/pom.xml, cqf-fhir-cr/pom.xml, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/dstu3/Dstu3MeasureProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/helper/DateHelper.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureProcessor.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/helper/DateHelperTest.java, cqf-fhir-jackson/pom.xml, cqf-fhir-jaxb/pom.xml, cqf-fhir-test/pom.xml, cqf-fhir-utility/pom.xml, docs/pom.xml, pom.xml
* Updated dependencies
* Replace removed APIs
=> Rev to  CR 3.0.0-PRE13, HAPI 6.10.0, FHIR Core 6.1.2.2

.gitignore, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/BreastCancerScreeningFHIR/tests/group/practitioner-group.json
caregaps service required some methods to not be package private so the main getReports method could be overriden
=> allow care-gaps method to be overriden

pom.xml
Implicitly updates to fhir core 6.1.2.2
=> Bump HAPI to 7.2.1

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/ExpandHelper.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/ValueSets.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/PackageVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/ExpandHelperTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/ValueSetsTest.java
[APHL-1169]
[APHL-1085] 
add expansion timestamp and utility for adding timestamp
[APHL-1169]: https://alphora.atlassian.net/browse/APHL-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APHL-1085]: https://alphora.atlassian.net/browse/APHL-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> expandHelper adds expansion timestamp when expanding Groupers

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/repository/InMemoryFhirRepository.java
=> Updated InMemoryFhirRepository to use HAPI's unsupported operation exception

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/constant/CareGapsConstants.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/constant/MeasureReportConstants.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapStatusEvaluator.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsBundleBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsProcessor.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/DataRequirementsTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/cql/MinimalProportionBooleanBasisSingleGroup.cql, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalProportionBooleanBasisMultiGroup.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalProportionBooleanBasisMultiGroupDifferentStatus.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalProportionBooleanBasisMultiGroupGroupImpNotation.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/resources/measure/MinimalProportionBooleanBasisMultiGroupNoGroupId.json, pom.xml
=> care-gap multi rate measure handling

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/AbstractKnowledgeArtifactVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/RetireVisitor.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/WithdrawVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/RetireVisitorTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/WithdrawVisitorTests.java, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r4/Bundle-retire.json
=> APHL-1075-retire_operation

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsTest.java
clean up structure of method to use lamda methods and external methods for more readable code
=> Lift measure parameter cleanup

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/ReleaseVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/dstu3/ReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/ReleaseVisitorTests.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r5/ReleaseVisitorTests.java
[APHL-1231] 
[APHL-1231]: https://alphora.atlassian.net/browse/APHL-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update tests and $release  to remove orphan references

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/visitor/DeleteVisitor.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/visitor/r4/DeleteVisitorTests.java, cqf-fhir-utility/src/test/resources/org/opencds/cqf/fhir/utility/visitor/r4/Bundle-delete.json
APHL-1076 Delete Operation for Retired Programs.
=> Add Delete Operation and Tests

cqf-fhir-benchmark/src/test/java/org/opencds/cqf/fhir/benchmark/Measures.java, cqf-fhir-benchmark/src/test/java/org/opencds/cqf/fhir/benchmark/MeasuresAdditionalData.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/Engines.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/EvaluationSettings.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/LibraryEngine.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/engine/retrieve/RetrieveSettings.java, cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/engine/terminology/TerminologySettings.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/EnginesTest.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/LibraryEngineTests.java, cqf-fhir-cr-cli/src/main/java/org/opencds/cqf/fhir/cr/cli/command/CqlCommand.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureProcessorEvaluateTest.java
* Revert Builder changes
* Add copy constructor for EvaluationSettings, RetrieveSettings, TerminologySettings
=> Copy constructors for settings classes

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/repository/ig/IgRepository.java
Added further documentation to IgRepository. Apply some RedHat formatting and fix a couple of spelling mistakes.
=> IgRepository Documentation

pom.xml
=> Update to Java 17

cqf-fhir-cr-spring/src/main/java/org/opencds/cqf/fhir/cr/spring/measure/MeasureConfiguration.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CollectDataService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureReportBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MultiMeasureService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/utils/R4MeasureServiceUtils.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/CollectData.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/Measure.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureMultipleSdeTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureEvaluationTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/utils/R4MeasureServiceUtilsTest.java
- Do not error for INDIVIDUAL reports for multiple SDEs. 
- Centralize the logic for converting report types to eval types.
- New and updated tests
Closes https://github.com/cqframework/clinical-reasoning/issues/592
=> Do not error for INDIVIDUAL reports for multiple SDEs. Centralize the logic for converting report types to eval types.

cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/MeasureOperationParameterConverterTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureReportBuilderTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/utils/R4MeasureServiceUtilsTest.java
- Miscellaneous improvements to test coverage.
Closes https://github.com/cqframework/clinical-reasoning/issues/612
=> Improve test coverage.

cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/CqlOptions.java, cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/EnginesTest.java
- Engines and EvaluationSettings 100% coverage.
Closes https://github.com/cqframework/clinical-reasoning/issues/610
=> Engines and EvaluationSettings 100% coverage.

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/common/PackageProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/BaseKnowledgeArtifactVisitor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/IValueSetExpansionCache.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/PackageVisitor.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/visitor/dstu3/PackageVisitorTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/visitor/r4/PackageVisitorTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/visitor/r5/PackageVisitorTests.java
[APHL-1180] Add an interface and implementation for VS Expansion Caching
Corresponding VSM PR: https://github.com/DBCG/aphl-vsm/pull/466
[APHL-1180]: https://alphora.atlassian.net/browse/APHL-1180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VS Expansion Caching

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/ReleaseVisitor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/VisitorHelper.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/visitor/dstu3/ReleaseVisitorTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/visitor/r4/ReleaseVisitorTests.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/visitor/r5/ReleaseVisitorTests.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/visitor/dstu3/Bundle-unversioned-dependency.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/visitor/r4/Bundle-unversioned-dependency.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/visitor/r5/Bundle-unversioned-dependency.json, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/client/TerminologyServerClient.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/matcher/ResourceMatcher.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/search/Searches.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/client/TerminologyServerClientTest.java
[APHL-1326] 
[APHL-1326]: https://alphora.atlassian.net/browse/APHL-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fallback to latest non draft version if an active version is unavailable during $release

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasureEvaluator.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/PopulationDef.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureDefBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureReportBuilder.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4PopulationBasisValidator.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/Measure.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureDefBuilderTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureReportTypeSubjectListTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureStratifierTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4PopulationBasisValidatorTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/utils/TestDataGenerator.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureTest/cql/SimpleCql.cql, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureTest/resources/measure/Measure-CohortBooleanStratComponent.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureTest/resources/measure/Measure-CohortBooleanStratComponentInvalid.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureTest/resources/measure/Measure-RatioResourceStratDifferentType.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MeasureTest/resources/measure/Measure-RatioResourceStratValue.json
=> component stratifier feature and tests

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4PopulationBasisValidator.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/Measure.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureEvaluationTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4PopulationBasisValidatorTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/SimpleMeasureProcessorTest.java, cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/SimpleMeasureProcessorWithEncounterProcedureMismatchTest.java, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/EncounterBasisMismatchWithProcedure/cql/EncounterBasisMismatchWithProcedure.cql, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/EncounterBasisMismatchWithProcedure/resources/library/EncounterBasisMismatchWithProcedure.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/EncounterBasisMismatchWithProcedure/resources/measure/EncounterBasisMismatchWithProcedure.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/EncounterBasisMismatchWithProcedure/tests/patient/denom-EXM108-2.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/EncounterBasisMismatchWithProcedure/tests/patient/denom-EXM108.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/EncounterBasisMismatchWithProcedure/tests/patient/numer-EXM108-2.json, cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/EncounterBasisMismatchWithProcedure/tests/patient/numer-EXM108.json
- Fix group basis error with more context and add more testing.
=> Fix group basis error with more context and add more testing.

.github/workflows/cdr_cr_check/trigger_and_poll_gitlab.py, .github/workflows/compile_against_cdr-cr.yml
- Small changes to activate previously present but deactivate pipeline functionality to compile against CQIS.
=> Turn on CQIS pipeline functionality.

cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/visitor/ReleaseVisitor.java
Update the ReleaseVisitor to add the cqf-resourceType extension to references to CodeSystem and ValueSet for R4 or R5 manifests
=> Releasevisitor add cqf-resourceType extension for ValueSet and CodeSystem

cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/cdshooks/BaseCdsCrMethod.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/cdshooks/CdsCrService.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/cdshooks/CdsCrServiceMethod.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/cdshooks/CdsServiceInterceptor.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/config/CrCdsHooksConfig.java, cqf-fhir-cr-hapi/src/test/java/org/opencds/cqf/fhir/cr/hapi/cdshooks/CdsCrServiceMethodTest.java, cqf-fhir-cr-hapi/src/test/java/org/opencds/cqf/fhir/cr/hapi/cdshooks/CdsServiceInterceptorTest.java
**Background:**
First instalment in a series of PR where the modifications aimed at improving test coverage for module cqf-fhir-cr-hapi
**What was done:**
- added tests for class CdsServiceInterceptor;
- added tests for class CdsCrServiceMethod;
=> Ep 20250620 hapi test coverage

cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/config/r4/CrR4Config.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/r4/IPackageServiceFactory.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/r4/crmi/PackageProvider.java, cqf-fhir-cr-hapi/src/test/java/org/opencds/cqf/fhir/cr/hapi/r4/PackageProviderIT.java, cqf-fhir-cr-hapi/src/test/resources/small-expansion-bundle.json, cqf-fhir-cr-hapi/src/test/resources/small-naive-expansion-bundle.json, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/crmi/KnowledgeArtifactProcessor.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/crmi/R4PackageService.java, cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/crmi/TransformProperties.java
- Added $package operation provider and service
- Added the operation to the R4 CR config
- Added documentation
- TODO - validate params and naive expansion behavior (noted in TODOs in codebase)
=> CRMI Package Operation (R4)

cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/repository/ClinicalIntelligenceHapiFhirRepository.java, cqf-fhir-cr-hapi/src/main/java/org/opencds/cqf/fhir/cr/hapi/repository/ClinicalIntelligenceRequestDetailsCloner.java, cqf-fhir-cr-hapi/src/test/java/org/opencds/cqf/fhir/cr/hapi/repository/ClinicalIntelligenceHapiFhirRepositoryTest.java, cqf-fhir-cr-hapi/src/test/java/org/opencds/cqf/fhir/cr/hapi/repository/ClinicalIntelligenceRequestDetailsClonerTest.java, cqf-fhir-cr-hapi/src/test/java/org/opencds/cqf/fhir/cr/hapi/repository/DetailsBuilderTest.java
**What was done:**
- Removed unused methods (DetailsBuilder);
- Refactored implementation to facilitate testing;
- Provided new tests increasing coverage.
=> increasing test coverage for package cr.hapi.repository

cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/adapter/dstu3/ImplementationGuideAdapter.java, cqf-fhir-utility/src/main/java/org/opencds/cqf/fhir/utility/adapter/r5/ImplementationGuideAdapter.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/adapter/dstu3/ImplementationGuideAdapterTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/adapter/r4/ImplementationGuideAdapterTest.java, cqf-fhir-utility/src/test/java/org/opencds/cqf/fhir/utility/adapter/r5/ImplementationGuideAdapterTest.java
Updated STU3 & R5 dependency gather. Added coverage tests
=> IG Adapter Patch
